
public class Pair { //to formulate the coordinate pair of each spot on the board
	int x;
	int y;
	Pair(int x, int y) {
		this.x = x;
		this.y = y;
	}
	@Override //an override generated by the Eclipse IDE
	public String toString() {
		return "[" + x + "," + y + "]";
	}
}
